/**
 * LLM explanation layer.
 *
 * The LLM is used ONLY for explanation/summarization of information the
 * deterministic pipeline already produced. It is never given the ability to
 * independently decide severity, and the prompt explicitly forbids
 * inventing facts, citations, or legal conclusions. If no API key is
 * configured, or the call fails/times out, a deterministic template-based
 * summary is returned instead so the app remains fully usable offline.
 */
import { settings } from "../config/settings";
import type { LlmExplanation, ProcessedText, RiskAssessment, RetrievedReference, ThreatSignal } from "../schemas/models";

interface ExplanationInput {
  processedText: ProcessedText;
  signals: ThreatSignal[];
  risk: RiskAssessment;
  references: RetrievedReference[];
}

function buildDeterministicSummary(input: ExplanationInput): string {
  const { signals, risk, references } = input;
  const lines: string[] = [];

  lines.push(
    `Deterministic summary (LLM unavailable): the rule-based analysis found ${signals.length} signal(s) ` +
      `and assessed severity as ${risk.severity}${risk.score !== null ? ` (score ${risk.score}/10)` : ""}.`
  );

  if (signals.length > 0) {
    const categories = Array.from(new Set(signals.map((s) => s.category))).join(", ");
    lines.push(`Categories detected: ${categories}.`);
  } else {
    lines.push("No categories were detected by the current rule-based detectors.");
  }

  if (risk.uncertainty.reasons.length > 0) {
    lines.push(`Uncertainty factors: ${risk.uncertainty.reasons.join(" ")}`);
  }

  if (references.length > 0) {
    lines.push(`Relevant reference material: ${references.map((r) => r.title).join("; ")}.`);
  }

  lines.push(
    "This summary is generated by fixed templates, not a language model, and should not be treated as legal or clinical advice."
  );

  return lines.join(" ");
}

function buildPrompt(input: ExplanationInput): { system: string; user: string } {
  const system = [
    "You are an assistant that explains an automated digital-abuse evidence analysis to a non-technical user.",
    "You MUST only use the structured information provided in the user message.",
    "Never invent facts, evidence, legal citations, statutes, or outcomes that are not present in the input.",
    "Never state that a crime has definitely occurred; the input signals are heuristic, not legal findings.",
    "Clearly communicate uncertainty where the input indicates it.",
    "Keep the tone calm, supportive, and factual. Output 3-6 short sentences of plain text, no markdown.",
  ].join(" ");

  const user = JSON.stringify(
    {
      verified_text_excerpt: input.processedText.normalizedText.slice(0, 2000),
      detected_signals: input.signals.map((s) => ({
        category: s.category,
        confidence: s.confidence,
        evidence_span: s.evidenceSpan,
      })),
      risk_assessment: {
        severity: input.risk.severity,
        score: input.risk.score,
        uncertainty: input.risk.uncertainty,
      },
      retrieved_references: input.references.map((r) => ({ title: r.title, source: r.source })),
    },
    null,
    2
  );

  return { system, user };
}

export async function generateExplanation(input: ExplanationInput): Promise<LlmExplanation> {
  const warnings: string[] = [];

  if (!settings.llm.enabled) {
    return {
      available: false,
      provider: null,
      model: null,
      summary: buildDeterministicSummary(input),
      usedFallback: true,
      warnings: ["LLM layer disabled via configuration (THREATLENS_LLM_ENABLED=false)."],
    };
  }

  if (!settings.llm.apiKey) {
    return {
      available: false,
      provider: null,
      model: null,
      summary: buildDeterministicSummary(input),
      usedFallback: true,
      warnings: ["No LLM API key configured (OPENAI_API_KEY). Showing deterministic summary instead."],
    };
  }

  const { system, user } = buildPrompt(input);
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), settings.llm.timeoutMs);

  try {
    const response = await fetch(`${settings.llm.apiBaseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${settings.llm.apiKey}`,
      },
      body: JSON.stringify({
        model: settings.llm.model,
        temperature: 0.2,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      const bodyText = await response.text().catch(() => "");
      warnings.push(`LLM API returned HTTP ${response.status}. Falling back to deterministic summary.`);
      if (bodyText) warnings.push(bodyText.slice(0, 200));
      return {
        available: false,
        provider: "openai_compatible",
        model: settings.llm.model,
        summary: buildDeterministicSummary(input),
        usedFallback: true,
        warnings,
      };
    }

    const data = (await response.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const content = data.choices?.[0]?.message?.content?.trim();

    if (!content) {
      warnings.push("LLM API returned an empty response. Falling back to deterministic summary.");
      return {
        available: false,
        provider: "openai_compatible",
        model: settings.llm.model,
        summary: buildDeterministicSummary(input),
        usedFallback: true,
        warnings,
      };
    }

    return {
      available: true,
      provider: "openai_compatible",
      model: settings.llm.model,
      summary: content,
      usedFallback: false,
      warnings,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return {
      available: false,
      provider: "openai_compatible",
      model: settings.llm.model,
      summary: buildDeterministicSummary(input),
      usedFallback: true,
      warnings: [`LLM call failed (${message}). Falling back to deterministic summary. No data was lost.`],
    };
  } finally {
    clearTimeout(timeout);
  }
}
